# Form implementation generated from reading ui file 'D:/Workbench/IAP_gui/uiap/uiap/ui/uiap.ui'
#
# Created by: PySide6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Form.resize(714, 592)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/icon/imgs/firmware_update.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        Form.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.serial_cfg_group_box = QtWidgets.QGroupBox(parent=Form)
        self.serial_cfg_group_box.setObjectName("serial_cfg_group_box")
        self.gridLayout = QtWidgets.QGridLayout(self.serial_cfg_group_box)
        self.gridLayout.setObjectName("gridLayout")
        self.serial_data_bits_cmb = QtWidgets.QComboBox(
            parent=self.serial_cfg_group_box
        )
        self.serial_data_bits_cmb.setObjectName("serial_data_bits_cmb")
        self.gridLayout.addWidget(self.serial_data_bits_cmb, 2, 1, 1, 2)
        self.serial_baud_rate_cmb = QtWidgets.QComboBox(
            parent=self.serial_cfg_group_box
        )
        self.serial_baud_rate_cmb.setMinimumSize(QtCore.QSize(0, 0))
        self.serial_baud_rate_cmb.setObjectName("serial_baud_rate_cmb")
        self.gridLayout.addWidget(self.serial_baud_rate_cmb, 1, 1, 1, 2)
        self.serial_port_lb = QtWidgets.QLabel(parent=self.serial_cfg_group_box)
        self.serial_port_lb.setObjectName("serial_port_lb")
        self.gridLayout.addWidget(self.serial_port_lb, 0, 0, 1, 1)
        self.serial_stop_bits_cmb = QtWidgets.QComboBox(
            parent=self.serial_cfg_group_box
        )
        self.serial_stop_bits_cmb.setObjectName("serial_stop_bits_cmb")
        self.gridLayout.addWidget(self.serial_stop_bits_cmb, 3, 1, 1, 2)
        self.serial_parity_cmb = QtWidgets.QComboBox(parent=self.serial_cfg_group_box)
        self.serial_parity_cmb.setObjectName("serial_parity_cmb")
        self.gridLayout.addWidget(self.serial_parity_cmb, 4, 1, 1, 2)
        self.serial_baud_rate_lb = QtWidgets.QLabel(parent=self.serial_cfg_group_box)
        self.serial_baud_rate_lb.setObjectName("serial_baud_rate_lb")
        self.gridLayout.addWidget(self.serial_baud_rate_lb, 1, 0, 1, 1)
        self.serial_data_bits_lb = QtWidgets.QLabel(parent=self.serial_cfg_group_box)
        self.serial_data_bits_lb.setObjectName("serial_data_bits_lb")
        self.gridLayout.addWidget(self.serial_data_bits_lb, 2, 0, 1, 1)
        self.serial_port_cmb = QtWidgets.QComboBox(parent=self.serial_cfg_group_box)
        self.serial_port_cmb.setObjectName("serial_port_cmb")
        self.gridLayout.addWidget(self.serial_port_cmb, 0, 1, 1, 2)
        self.serial_stop_bits_lb = QtWidgets.QLabel(parent=self.serial_cfg_group_box)
        self.serial_stop_bits_lb.setObjectName("serial_stop_bits_lb")
        self.gridLayout.addWidget(self.serial_stop_bits_lb, 3, 0, 1, 1)
        self.serial_flow_ctrl_lb = QtWidgets.QLabel(parent=self.serial_cfg_group_box)
        self.serial_flow_ctrl_lb.setObjectName("serial_flow_ctrl_lb")
        self.gridLayout.addWidget(self.serial_flow_ctrl_lb, 5, 0, 1, 1)
        self.serial_parity_lb = QtWidgets.QLabel(parent=self.serial_cfg_group_box)
        self.serial_parity_lb.setObjectName("serial_parity_lb")
        self.gridLayout.addWidget(self.serial_parity_lb, 4, 0, 1, 1)
        self.serial_flow_ctrl_cmb = QtWidgets.QComboBox(
            parent=self.serial_cfg_group_box
        )
        self.serial_flow_ctrl_cmb.setObjectName("serial_flow_ctrl_cmb")
        self.gridLayout.addWidget(self.serial_flow_ctrl_cmb, 5, 1, 1, 2)
        self.serial_rts_chk = QtWidgets.QCheckBox(parent=self.serial_cfg_group_box)
        self.serial_rts_chk.setObjectName("serial_rts_chk")
        self.gridLayout.addWidget(self.serial_rts_chk, 6, 0, 1, 1)
        self.serial_open_btn = QtWidgets.QPushButton(parent=self.serial_cfg_group_box)
        self.serial_open_btn.setObjectName("serial_open_btn")
        self.gridLayout.addWidget(self.serial_open_btn, 8, 0, 1, 3)
        self.serial_dtr_chk = QtWidgets.QCheckBox(parent=self.serial_cfg_group_box)
        self.serial_dtr_chk.setObjectName("serial_dtr_chk")
        self.gridLayout.addWidget(self.serial_dtr_chk, 6, 1, 1, 1)
        self.horizontalLayout_9.addWidget(self.serial_cfg_group_box)
        self.firmware_cfg_group_box = QtWidgets.QGroupBox(parent=Form)
        self.firmware_cfg_group_box.setObjectName("firmware_cfg_group_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.firmware_cfg_group_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.firmware_selected_chk_2 = QtWidgets.QCheckBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_selected_chk_2.setObjectName("firmware_selected_chk_2")
        self.gridLayout_2.addWidget(self.firmware_selected_chk_2, 3, 0, 1, 1)
        self.firmware_crypto_lb = QtWidgets.QLabel(parent=self.firmware_cfg_group_box)
        self.firmware_crypto_lb.setObjectName("firmware_crypto_lb")
        self.gridLayout_2.addWidget(self.firmware_crypto_lb, 0, 5, 1, 1)
        self.firmware_selected_chk_5 = QtWidgets.QCheckBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_selected_chk_5.setObjectName("firmware_selected_chk_5")
        self.gridLayout_2.addWidget(self.firmware_selected_chk_5, 6, 0, 1, 1)
        self.firmware_crypto_cmb_2 = QtWidgets.QComboBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_crypto_cmb_2.setObjectName("firmware_crypto_cmb_2")
        self.gridLayout_2.addWidget(self.firmware_crypto_cmb_2, 3, 5, 1, 1)
        self.firmware_open_file_tb_7 = QtWidgets.QToolButton(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_open_file_tb_7.setObjectName("firmware_open_file_tb_7")
        self.gridLayout_2.addWidget(self.firmware_open_file_tb_7, 9, 3, 1, 1)
        self.firmware_address_lb = QtWidgets.QLabel(parent=self.firmware_cfg_group_box)
        self.firmware_address_lb.setObjectName("firmware_address_lb")
        self.gridLayout_2.addWidget(self.firmware_address_lb, 0, 4, 1, 1)
        self.firmware_path_le_3 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_path_le_3.setObjectName("firmware_path_le_3")
        self.gridLayout_2.addWidget(self.firmware_path_le_3, 4, 1, 1, 2)
        self.firmware_address_le_6 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_address_le_6.setObjectName("firmware_address_le_6")
        self.gridLayout_2.addWidget(self.firmware_address_le_6, 7, 4, 1, 1)
        self.firmware_crypto_cmb_1 = QtWidgets.QComboBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_crypto_cmb_1.setObjectName("firmware_crypto_cmb_1")
        self.gridLayout_2.addWidget(self.firmware_crypto_cmb_1, 2, 5, 1, 1)
        self.firmware_open_file_tb_5 = QtWidgets.QToolButton(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_open_file_tb_5.setObjectName("firmware_open_file_tb_5")
        self.gridLayout_2.addWidget(self.firmware_open_file_tb_5, 6, 3, 1, 1)
        self.firmware_crypto_cmb_4 = QtWidgets.QComboBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_crypto_cmb_4.setObjectName("firmware_crypto_cmb_4")
        self.gridLayout_2.addWidget(self.firmware_crypto_cmb_4, 5, 5, 1, 1)
        self.firmware_address_le_4 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_address_le_4.setObjectName("firmware_address_le_4")
        self.gridLayout_2.addWidget(self.firmware_address_le_4, 5, 4, 1, 1)
        self.firmware_address_le_7 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_address_le_7.setObjectName("firmware_address_le_7")
        self.gridLayout_2.addWidget(self.firmware_address_le_7, 9, 4, 1, 1)
        self.firmware_crypto_cmb_6 = QtWidgets.QComboBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_crypto_cmb_6.setObjectName("firmware_crypto_cmb_6")
        self.gridLayout_2.addWidget(self.firmware_crypto_cmb_6, 9, 5, 1, 1)
        self.firmware_open_file_tb_4 = QtWidgets.QToolButton(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_open_file_tb_4.setObjectName("firmware_open_file_tb_4")
        self.gridLayout_2.addWidget(self.firmware_open_file_tb_4, 5, 3, 1, 1)
        self.firmware_path_lb = QtWidgets.QLabel(parent=self.firmware_cfg_group_box)
        self.firmware_path_lb.setObjectName("firmware_path_lb")
        self.gridLayout_2.addWidget(self.firmware_path_lb, 0, 1, 1, 3)
        self.firmware_selected_chk_1 = QtWidgets.QCheckBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_selected_chk_1.setObjectName("firmware_selected_chk_1")
        self.gridLayout_2.addWidget(self.firmware_selected_chk_1, 2, 0, 1, 1)
        self.firmware_address_le_5 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_address_le_5.setObjectName("firmware_address_le_5")
        self.gridLayout_2.addWidget(self.firmware_address_le_5, 6, 4, 1, 1)
        self.firmware_selected_chk_0 = QtWidgets.QCheckBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_selected_chk_0.setChecked(False)
        self.firmware_selected_chk_0.setObjectName("firmware_selected_chk_0")
        self.gridLayout_2.addWidget(self.firmware_selected_chk_0, 1, 0, 1, 1)
        self.firmware_crypto_cmb_7 = QtWidgets.QComboBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_crypto_cmb_7.setObjectName("firmware_crypto_cmb_7")
        self.gridLayout_2.addWidget(self.firmware_crypto_cmb_7, 7, 5, 1, 1)
        self.firmware_open_file_tb_3 = QtWidgets.QToolButton(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_open_file_tb_3.setObjectName("firmware_open_file_tb_3")
        self.gridLayout_2.addWidget(self.firmware_open_file_tb_3, 4, 3, 1, 1)
        self.firmware_path_le_5 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_path_le_5.setObjectName("firmware_path_le_5")
        self.gridLayout_2.addWidget(self.firmware_path_le_5, 6, 1, 1, 2)
        self.firmware_crypto_cmb_5 = QtWidgets.QComboBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_crypto_cmb_5.setObjectName("firmware_crypto_cmb_5")
        self.gridLayout_2.addWidget(self.firmware_crypto_cmb_5, 6, 5, 1, 1)
        self.firmware_selected_lb = QtWidgets.QLabel(parent=self.firmware_cfg_group_box)
        self.firmware_selected_lb.setObjectName("firmware_selected_lb")
        self.gridLayout_2.addWidget(self.firmware_selected_lb, 0, 0, 1, 1)
        self.firmware_selected_chk_6 = QtWidgets.QCheckBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_selected_chk_6.setObjectName("firmware_selected_chk_6")
        self.gridLayout_2.addWidget(self.firmware_selected_chk_6, 7, 0, 1, 1)
        self.firmware_path_le_0 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_path_le_0.setMinimumSize(QtCore.QSize(150, 0))
        self.firmware_path_le_0.setObjectName("firmware_path_le_0")
        self.gridLayout_2.addWidget(self.firmware_path_le_0, 1, 1, 1, 2)
        self.firmware_address_le_3 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_address_le_3.setObjectName("firmware_address_le_3")
        self.gridLayout_2.addWidget(self.firmware_address_le_3, 4, 4, 1, 1)
        self.firmware_crypto_cmb_3 = QtWidgets.QComboBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_crypto_cmb_3.setObjectName("firmware_crypto_cmb_3")
        self.gridLayout_2.addWidget(self.firmware_crypto_cmb_3, 4, 5, 1, 1)
        self.firmware_open_file_tb_0 = QtWidgets.QToolButton(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_open_file_tb_0.setObjectName("firmware_open_file_tb_0")
        self.gridLayout_2.addWidget(self.firmware_open_file_tb_0, 1, 3, 1, 1)
        self.firmware_address_le_2 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_address_le_2.setObjectName("firmware_address_le_2")
        self.gridLayout_2.addWidget(self.firmware_address_le_2, 3, 4, 1, 1)
        self.firmware_selected_chk_7 = QtWidgets.QCheckBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_selected_chk_7.setObjectName("firmware_selected_chk_7")
        self.gridLayout_2.addWidget(self.firmware_selected_chk_7, 9, 0, 1, 1)
        self.firmware_address_le_0 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_address_le_0.setMinimumSize(QtCore.QSize(75, 0))
        self.firmware_address_le_0.setText("")
        self.firmware_address_le_0.setObjectName("firmware_address_le_0")
        self.gridLayout_2.addWidget(self.firmware_address_le_0, 1, 4, 1, 1)
        self.firmware_crypto_cmb_0 = QtWidgets.QComboBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_crypto_cmb_0.setObjectName("firmware_crypto_cmb_0")
        self.gridLayout_2.addWidget(self.firmware_crypto_cmb_0, 1, 5, 1, 1)
        self.firmware_address_le_1 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_address_le_1.setObjectName("firmware_address_le_1")
        self.gridLayout_2.addWidget(self.firmware_address_le_1, 2, 4, 1, 1)
        self.firmware_selected_chk_3 = QtWidgets.QCheckBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_selected_chk_3.setObjectName("firmware_selected_chk_3")
        self.gridLayout_2.addWidget(self.firmware_selected_chk_3, 4, 0, 1, 1)
        self.firmware_open_file_tb_2 = QtWidgets.QToolButton(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_open_file_tb_2.setObjectName("firmware_open_file_tb_2")
        self.gridLayout_2.addWidget(self.firmware_open_file_tb_2, 3, 3, 1, 1)
        self.firmware_path_le_2 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_path_le_2.setObjectName("firmware_path_le_2")
        self.gridLayout_2.addWidget(self.firmware_path_le_2, 3, 1, 1, 2)
        self.firmware_selected_chk_4 = QtWidgets.QCheckBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_selected_chk_4.setObjectName("firmware_selected_chk_4")
        self.gridLayout_2.addWidget(self.firmware_selected_chk_4, 5, 0, 1, 1)
        self.firmware_path_le_4 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_path_le_4.setObjectName("firmware_path_le_4")
        self.gridLayout_2.addWidget(self.firmware_path_le_4, 5, 1, 1, 2)
        self.firmware_path_le_6 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_path_le_6.setObjectName("firmware_path_le_6")
        self.gridLayout_2.addWidget(self.firmware_path_le_6, 7, 1, 1, 2)
        self.firmware_open_file_tb_1 = QtWidgets.QToolButton(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_open_file_tb_1.setObjectName("firmware_open_file_tb_1")
        self.gridLayout_2.addWidget(self.firmware_open_file_tb_1, 2, 3, 1, 1)
        self.firmware_open_file_tb_6 = QtWidgets.QToolButton(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_open_file_tb_6.setObjectName("firmware_open_file_tb_6")
        self.gridLayout_2.addWidget(self.firmware_open_file_tb_6, 7, 3, 1, 1)
        self.firmware_path_le_7 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_path_le_7.setObjectName("firmware_path_le_7")
        self.gridLayout_2.addWidget(self.firmware_path_le_7, 9, 1, 1, 2)
        self.firmware_path_le_1 = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_path_le_1.setObjectName("firmware_path_le_1")
        self.gridLayout_2.addWidget(self.firmware_path_le_1, 2, 1, 1, 2)
        self.gridLayout_2.setColumnStretch(1, 9)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.firmware_read_btn = QtWidgets.QPushButton(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_read_btn.setObjectName("firmware_read_btn")
        self.gridLayout_4.addWidget(self.firmware_read_btn, 6, 0, 1, 3)
        self.firmware_read_size_le = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_read_size_le.setObjectName("firmware_read_size_le")
        self.gridLayout_4.addWidget(self.firmware_read_size_le, 5, 2, 1, 1)
        self.firmware_transfer_protocol_cmb = QtWidgets.QComboBox(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_transfer_protocol_cmb.setObjectName(
            "firmware_transfer_protocol_cmb"
        )
        self.gridLayout_4.addWidget(self.firmware_transfer_protocol_cmb, 2, 2, 1, 1)
        self.firmware_update_btn = QtWidgets.QPushButton(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_update_btn.setObjectName("firmware_update_btn")
        self.gridLayout_4.addWidget(self.firmware_update_btn, 3, 0, 1, 3)
        self.firmware_read_start_address_lb = QtWidgets.QLabel(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_read_start_address_lb.setObjectName(
            "firmware_read_start_address_lb"
        )
        self.gridLayout_4.addWidget(self.firmware_read_start_address_lb, 4, 0, 1, 2)
        self.firmware_read_start_address_le = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_read_start_address_le.setMinimumSize(QtCore.QSize(75, 0))
        self.firmware_read_start_address_le.setText("")
        self.firmware_read_start_address_le.setObjectName(
            "firmware_read_start_address_le"
        )
        self.gridLayout_4.addWidget(self.firmware_read_start_address_le, 4, 2, 1, 1)
        self.firmware_read_size_lb = QtWidgets.QLabel(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_read_size_lb.setObjectName("firmware_read_size_lb")
        self.gridLayout_4.addWidget(self.firmware_read_size_lb, 5, 0, 1, 2)
        self.firmware_combine_btn = QtWidgets.QPushButton(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_combine_btn.setObjectName("firmware_combine_btn")
        self.gridLayout_4.addWidget(self.firmware_combine_btn, 1, 0, 1, 3)
        self.firmware_fill_byte_le = QtWidgets.QLineEdit(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_fill_byte_le.setText("")
        self.firmware_fill_byte_le.setObjectName("firmware_fill_byte_le")
        self.gridLayout_4.addWidget(self.firmware_fill_byte_le, 0, 2, 1, 1)
        self.firmware_transfer_protocol_lb = QtWidgets.QLabel(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_transfer_protocol_lb.setLayoutDirection(
            QtCore.Qt.LayoutDirection.LeftToRight
        )
        self.firmware_transfer_protocol_lb.setObjectName(
            "firmware_transfer_protocol_lb"
        )
        self.gridLayout_4.addWidget(self.firmware_transfer_protocol_lb, 2, 0, 1, 2)
        self.firmware_fill_byte_lb = QtWidgets.QLabel(
            parent=self.firmware_cfg_group_box
        )
        self.firmware_fill_byte_lb.setObjectName("firmware_fill_byte_lb")
        self.gridLayout_4.addWidget(self.firmware_fill_byte_lb, 0, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.firmware_cfg_group_box)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 9)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.horizontalLayout_9.addWidget(self.firmware_cfg_group_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.tabWidget.setObjectName("tabWidget")
        self.serial_tab = QtWidgets.QWidget()
        self.serial_tab.setObjectName("serial_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.serial_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.serial_rx_tx_pte = QtWidgets.QPlainTextEdit(parent=self.serial_tab)
        self.serial_rx_tx_pte.setMinimumSize(QtCore.QSize(0, 0))
        self.serial_rx_tx_pte.setReadOnly(True)
        self.serial_rx_tx_pte.setObjectName("serial_rx_tx_pte")
        self.verticalLayout_3.addWidget(self.serial_rx_tx_pte)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.serial_tx_pte = QtWidgets.QPlainTextEdit(parent=self.serial_tab)
        self.serial_tx_pte.setObjectName("serial_tx_pte")
        self.horizontalLayout.addWidget(self.serial_tx_pte)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.serial_rx_tx_hex_chk = QtWidgets.QCheckBox(parent=self.serial_tab)
        self.serial_rx_tx_hex_chk.setObjectName("serial_rx_tx_hex_chk")
        self.verticalLayout.addWidget(self.serial_rx_tx_hex_chk)
        self.serial_tx_hex_chk = QtWidgets.QCheckBox(parent=self.serial_tab)
        self.serial_tx_hex_chk.setObjectName("serial_tx_hex_chk")
        self.verticalLayout.addWidget(self.serial_tx_hex_chk)
        self.serial_clear_btn = QtWidgets.QPushButton(parent=self.serial_tab)
        self.serial_clear_btn.setObjectName("serial_clear_btn")
        self.verticalLayout.addWidget(self.serial_clear_btn)
        self.serial_send_btn = QtWidgets.QPushButton(parent=self.serial_tab)
        self.serial_send_btn.setObjectName("serial_send_btn")
        self.verticalLayout.addWidget(self.serial_send_btn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(0, 9)
        self.verticalLayout_3.setStretch(1, 1)
        self.tabWidget.addTab(self.serial_tab, "")
        self.log_tab = QtWidgets.QWidget()
        self.log_tab.setObjectName("log_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.log_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.log_pte = QtWidgets.QPlainTextEdit(parent=self.log_tab)
        self.log_pte.setMinimumSize(QtCore.QSize(0, 250))
        self.log_pte.setReadOnly(True)
        self.log_pte.setObjectName("log_pte")
        self.gridLayout_5.addWidget(self.log_pte, 0, 0, 1, 1)
        self.tabWidget.addTab(self.log_tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "UIAP"))
        self.serial_cfg_group_box.setTitle(_translate("Form", "串口配置"))
        self.serial_port_lb.setText(_translate("Form", "端口号"))
        self.serial_baud_rate_lb.setText(_translate("Form", "波特率"))
        self.serial_data_bits_lb.setText(_translate("Form", "数据位"))
        self.serial_stop_bits_lb.setText(_translate("Form", "停止位"))
        self.serial_flow_ctrl_lb.setText(_translate("Form", "流控制"))
        self.serial_parity_lb.setText(_translate("Form", "校验位"))
        self.serial_rts_chk.setText(_translate("Form", "RTS"))
        self.serial_open_btn.setText(_translate("Form", "打开串口"))
        self.serial_dtr_chk.setText(_translate("Form", "DTR"))
        self.firmware_cfg_group_box.setTitle(_translate("Form", "固件配置"))
        self.firmware_selected_chk_2.setText(_translate("Form", "#2"))
        self.firmware_crypto_lb.setText(_translate("Form", "加密算法"))
        self.firmware_selected_chk_5.setText(_translate("Form", "#5"))
        self.firmware_open_file_tb_7.setText(_translate("Form", "..."))
        self.firmware_address_lb.setText(_translate("Form", "地址"))
        self.firmware_open_file_tb_5.setText(_translate("Form", "..."))
        self.firmware_open_file_tb_4.setText(_translate("Form", "..."))
        self.firmware_path_lb.setText(_translate("Form", "路径"))
        self.firmware_selected_chk_1.setText(_translate("Form", "#1"))
        self.firmware_selected_chk_0.setText(_translate("Form", "#0"))
        self.firmware_open_file_tb_3.setText(_translate("Form", "..."))
        self.firmware_selected_lb.setText(_translate("Form", "NO."))
        self.firmware_selected_chk_6.setText(_translate("Form", "#6"))
        self.firmware_open_file_tb_0.setText(_translate("Form", "..."))
        self.firmware_selected_chk_7.setText(_translate("Form", "#7"))
        self.firmware_selected_chk_3.setText(_translate("Form", "#3"))
        self.firmware_open_file_tb_2.setText(_translate("Form", "..."))
        self.firmware_selected_chk_4.setText(_translate("Form", "#4"))
        self.firmware_open_file_tb_1.setText(_translate("Form", "..."))
        self.firmware_open_file_tb_6.setText(_translate("Form", "..."))
        self.firmware_read_btn.setText(_translate("Form", "固件读取"))
        self.firmware_update_btn.setText(_translate("Form", "固件升级"))
        self.firmware_read_start_address_lb.setText(_translate("Form", "起始地址"))
        self.firmware_read_size_lb.setText(_translate("Form", "大小"))
        self.firmware_combine_btn.setText(_translate("Form", "固件合并"))
        self.firmware_transfer_protocol_lb.setText(_translate("Form", "传输协议"))
        self.firmware_fill_byte_lb.setText(_translate("Form", "固件填充"))
        self.serial_rx_tx_hex_chk.setText(_translate("Form", "HEX 显示"))
        self.serial_tx_hex_chk.setText(_translate("Form", "HEX 发送"))
        self.serial_clear_btn.setText(_translate("Form", "清空"))
        self.serial_send_btn.setText(_translate("Form", "发送"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.serial_tab), _translate("Form", "串口")
        )
        self.log_tab.setAccessibleName(_translate("Form", "a"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.log_tab), _translate("Form", "日志")
        )
